DEVELOPMENT: 1
DATABASE:
  name: "openstack_citest"
  engine: "postgresql"
  host: "localhost"
  port: "5432"
  user: "openstack_citest"
  passwd: "openstack_citest"
API_LOG: "logs/api.log"
APP_LOG: "logs/app.log"
APP_LOGLEVEL: "ERROR"
RPC_CONSUMER_LOG_PATH: "logs/receiverd.log"
ASSASSIN_LOG_PATH: "logs/assassind.log"
STATS_LOGS_PATH: "logs/"
LCM_SERIALIZERS_CONCURRENCY_FACTOR: 1
